spring:
#  config:
#    import: optional:classpath:application.yaml  # 确保当前模块配置优先
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
  #短链接跳转失败时的前端页面响应
    view:
      prefix: /templates/
      suffix: .html

server:
  port: 8001

#short-link:
#  statistic:
#    locale:
#      amap-key:824c511f0997586ea016f979fdb23087

short-link:
  domain:
    default: nurl.ink:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
